#!/data/data/com.termux/files/usr/bin/bash

#Sometimes the same command has to be run over all 66 books. This is just a loop to enter the command. Saves time compared to entering it manually over and over, 66 times.

source ./specs.adom #variables

Len=${#books[@]} #length books array

for (( i=0; i<${Len}; i++ )); do 
  #echo ${books[$i]}

#deleted:    vCount/48-Galatians-rpt
#deleted:    vCount/48-Galatians-spec

  git rm --cached "vCount/${books[$i]}-rpt"
  git rm --cached "vCount/${books[$i]}-spec"
done

#array element accessed with ${ArrayName[subscript]}

#git rm --cached 06-Joshua/999-brefspec
